### ISSUE TITLE
Please, add default constructor for org.springframework.cloud.servicebroker.model.catalog.Plan

### ISSUE THREAD

**Issue by IvaDonchev** [spring-cloud/spring-cloud-open-service-broker#121] opened 2018-09-14 11:24 UTC
I have encountered the following issue: 

`Type definition error: [simple type, class org.springframework.cloud.servicebroker.model.catalog.Plan]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.cloud.servicebroker.model.catalog.Plan` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

 at [Source: (PushbackInputStream); line: 7, column: 7] (through reference chain: com.sap.cloud.cf.destinations.servicebroker.clients.cloudcontroller.Page["resources"]->java.util.ArrayList[0]->com.sap.cloud.cf.destinations.servicebroker.clients.cloudcontroller.Resource["entity"])

 

org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class org.springframework.cloud.servicebroker.model.catalog.Plan]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.cloud.servicebroker.model.catalog.Plan` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

 at [Source: (PushbackInputStream); line: 7, column: 7] (through reference chain: com.sap.cloud.cf.destinations.servicebroker.clients.cloudcontroller.Page["resources"]->java.util.ArrayList[0]->com.sap.cloud.cf.destinations.servicebroker.clients.cloudcontroller.Resource["entity"])

            at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:238) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]`

**Comment by IvaDonchev** [comment] 2018-09-14 11:26
I'm using spring-security-oauth2-2.2.1.RELEASE.jar:na] and spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE and Open service broker API

**Comment by AlbertoImpl** [comment] 2018-09-17 10:50
Hi @IvaDonchev, 
Thanks for reporting the issue.

This problem was fixed on the latest commit, so the latest SNAPSHOT should have it fixed.
We will be cutting a release soon.

Thanks!

**Comment by IvaDonchev** [comment] 2018-09-17 11:56
Great :) Thanks. I have been struggling with one more issue and I will create a bug for it in a minute.

**Comment by IvaDonchev** [comment] 2018-09-17 11:58
Could you check also the other classes whether some other class that needs to be deserialised is missing a default constructor?

**Comment by AlbertoImpl** [comment] 2018-09-17 12:01
I want to believe that all the classes were added @IvaDonchev, let us know if you find they weren't.
Thanks!

**Comment by royclarkson** [comment] 2018-09-17 18:04
@IvaDonchev please see this commit and let us know if it doesn't cover something that you need. https://github.com/spring-cloud/spring-cloud-open-service-broker/commit/77eb38d8d8ba87ebaf781ce4dfaa2f08568f90ec

**Comment by IvaDonchev** [comment] 2018-09-25 11:26
Hi, which snapshot could I use? I used 2.0.1 Release but I got:
`   2018-09-25T14:17:44.22+0300 [APP/PROC/WEB/0] ERR  Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.setConfigurers(java.util.List); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.servicebroker.autoconfigure.web.ApiVersionWebMvcAutoConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.servicebroker.autoconfigure.web.ApiVersionWebMvcAutoConfiguration$$EnhancerBySpringCGLIB$$12e9a326]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.servicebroker.autoconfigure.web.ApiVersionWebMvcAutoConfiguration$$EnhancerBySpringCGLIB$$12e9a326.<init>()`

**Comment by royclarkson** [comment] 2018-09-27 03:41
Try `2.1.0.BUILD-SNAPSHOT`. Thanks.

**Comment by IvaDonchev** [comment] 2018-10-02 08:54
Hi,

Which repository should I use? I tried with:

```
      <repositories>
	    <repository>
	      <id>org.springframework.cloud</id>
	      <url>https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-open-service-broker-core</url>
	    </repository>
	  </repositories>

```
And
```

		<!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-open-service-broker-core -->
		<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-open-service-broker-core</artifactId>
		    <version>2.1.0.BUILD-SNAPSHOT</version>
		</dependency>
```

But I get:

```
[WARNING] The POM for org.springframework.cloud:spring-cloud-open-service-broker-core:jar:2.1.0.BUILD-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for junit:junit-dep:jar:4.9.1-SNAPSHOT is missing, no dependency information available
```
Because maven doesn't search in the correct repository.
Is it possible to release the new version. This really blocks my delivery.

Best regards,
Iva

**Comment by IvaDonchev** [comment] 2018-10-02 12:33
Hi Alberto,

Thanks for the answer. And when is expected the next release?

Best regards,
Iva

**Comment by royclarkson** [comment] 2018-10-02 15:06
I just published `2.1.0.M1` that includes these changes, and you'll need to use `<url>https://repo.spring.io/milestone</url>` repo to pull in the dependency.

**Comment by royclarkson** [comment] 2018-10-02 15:20
Duplicate of #110

**Closed by royclarkson** 2018-10-02 15:20 UTC
Labels: accepted, duplicate
