### ISSUE TITLE
Spring Boot 2.5.x compatibility

### ISSUE THREAD

**Issue by dennis-menge** [spring-cloud/spring-cloud-open-service-broker#327] opened 2021-08-09 15:47 UTC
The current state does not support Spring Boot 2.5 due to missing JSON property mappings.

**Comment by royclarkson** [comment] 2021-08-31 18:31
Thanks for reporting. We'll work on releasing a Boot 2.5 compatible version of SCOSB.

**Comment by royclarkson** [comment] 2021-09-29 21:12
closed in d9058126c6bb6a7a36903e355fc9c0e61a9017f6

**Closed by royclarkson** 2021-09-29 21:12 UTC

**Comment by royclarkson** [comment] 2021-09-29 21:17
Commit message should be for Boot 2.5.5 (not 3.5.5). Apologies for the confusion.

**Comment by royclarkson** [comment] 2021-09-30 16:46
Duplicate of #320  and #330
