### ISSUE TITLE
2.16 Spec version support

### ISSUE THREAD

**Issue by andreaAlkalay** [spring-cloud/spring-cloud-open-service-broker#307] opened 2020-11-11 09:51 UTC
Hi,

When will a release which supports the 2.16 OSB spec version be available?

Thanks
Andrea.

**Comment by royclarkson** [comment] 2020-11-11 13:49
@andreaAlkalay thanks for the inquiry. We currently do not have a plan for supporting 2.16 OSB, however we're happy to consider one. The [latest CAPI release is still on 2.15](https://source.vmware.com/portal/pages/RnD/mapbu-distribution-lists), so it hasn't been a requested feature yet. If there are specific additions or changes that you'd like to see, please open an issue and label it with `OSB API 2.16`. Additionally, we're always open to community contributions.

**Comment by andreaAlkalay** [comment] 2020-11-11 17:58
Hi,
I would like to request to add the support in labelling service instances:
https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md#v216
https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#service-instance-metadata

Thanks,
Andrea.

**Comment by andreaAlkalay** [comment] 2020-11-22 13:58
Hi @royclarkson - I would like to contribute the metadata labels I have requested above.
What should I do in order to be able to create a PR?

Thanks!
Andrea.

**Comment by royclarkson** [comment] 2020-11-30 17:00
@andreaAlkalay we welcome PRs from the community! For any new features, please create a new issue for that specific feature. Include the links to the OSB API spec and add a short description. Add the OSB API 2.16 to the new issue. After the issue is open, then you can work on a PR.

**Comment by andreaAlkalay** [comment] 2020-11-30 18:32
Hi,
Thanks for the information 👍 
I have created https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/311
But I can't seem to add the label..

Andrea.

**Comment by royclarkson** [comment] 2020-11-30 18:45
@andreaAlkalay thanks. I've added the label. I'm also going to close this issue in favor of adding specific issues for each 2.16 feature. We'll begin adding those and consider them for a Spring Cloud Open Service Broker 3.3 release.

**Closed by royclarkson** 2020-11-30 18:45 UTC
