### ISSUE TITLE
context.getProperty("organization_guid") returns null for "cloudfoundry" platform

### ISSUE THREAD

**Issue by IvaDonchev** [spring-cloud/spring-cloud-open-service-broker#122] opened 2018-09-17 12:21 UTC
I have a component test which first creates a request to my service broker. This is the body:
             
 ` JsonObject jsonObject = Json.createObjectBuilder().add("service_id", SERVICE_ID)
                           .add("plan_id", CatalogConfig.PLAN_LITE_ID)
                           .add("context", Json.createObjectBuilder()
                                         .add("platform", "cloudfoundry")
                                         .add("global_account_id", "some_guid_here")
                                         .add("subaccount_id", "some_guid_here")
                                         .add("tenant_id", "some_tenant_here")
                                         .add("origin", "cloudfoundry")
                                         .add("organization_guid", ORG_GUID)
                                         .add("space_guid", "some_guid_here"))
                           .add("organization_guid", ORG_GUID)
                           .add("space_guid", "some_guid_here").build();
              return jsonObject;`

In my service broker I'm using:
`String organizationGuid = String.valueOf(context.getProperty("organization_guid"));
  String spaceGuid = String.valueOf(context.getProperty("space_guid"));`

And I get:  null for both variables
 
I debugged it and I could see that when the context object is created it looks like this:
 
 
`2018-09-13` 09:11:12.550  INFO 23031 --- [           main]  : Context{platform='cloudfoundry', properties={tenant_id=d0e9f4f6-ed85-4def-8afc-5a65a2a99d5d, global_account_id=7c0b544a-7d08-4f7c-961a-58d68b136eec, origin=cloudfoundry, subaccount_id=d0e9f4f6-ed85-4def-8afc-5a65a2a99d5d}}CloudFoundryContext{organizationGuid='qwweq', `spaceGuid='2131'}`

In my communication with Florian Mueller, he suggested that the issue is because I use platform='cloudfoundry'. However, there is such use case and this should work.

For now I could only use the deprecated methods:

`String` organizationGuid = request.getOrganizationGuid();
String spaceGuid = request.getSpaceGuid();`

**Comment by scottfrederick** [comment] 2018-09-17 15:33
@IvaDonchev This looks like a duplicate of #102. Please use the `2.0.1.RELEASE` with the change mentioned there, along with the suggested usage in the comments. Feel free to re-open this issue wiht additional detail if this doesn't work for you.

**Closed by scottfrederick** 2018-09-17 15:33 UTC
